# Generated by Django 4.2.2 on 2023-07-05 11:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Qty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                # ('QR Code', models.ImageField(upload_to='qrcodes/')),
            ],
        ),
    #     migrations.AddField(
    #     model_name='features',
    #     name='Rack_id',
    #     field=models.IntegerField(max_length=255, null=False, blank=False,default=1),
    # ),
        
    ]
