# Generated by Django 4.2.2 on 2023-07-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Racks',
            fields=[
                ('Rid', models.IntegerField(primary_key=True, serialize=False)),
                ('Rname', models.CharField(max_length=10)),
                ('Rqty', models.IntegerField(default=0)),
            ],
        ),
    ]
