# Generated by Django 4.2.2 on 2023-07-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_features_created_by_features_rack_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='features',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('Qty', models.IntegerField(default=0)),
                ('box_id', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='myapp.features')),
            ],
        ),
    ]
