# Generated by Django 4.2.2 on 2023-10-18 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0004_alter_features_id_alter_features_name_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="features",
            name="created_by",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="myapp_features",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
