# Generated by Django 4.2.2 on 2023-10-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_features_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="features",
            name="qr_code_image",
            field=models.ImageField(blank=True, upload_to="qr_codes"),
        ),
    ]
