# Generated by Django 4.2.2 on 2023-11-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_features_qr_code_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="features",
            name="qr_code_image",
        ),
        migrations.AddField(
            model_name="features",
            name="qr_code_image_data",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
